// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function EnsureBookDir(arg1, arg2) {
  return window['go']['main']['App']['EnsureBookDir'](arg1, arg2);
}

export function GetTextbooks() {
  return window['go']['main']['App']['GetTextbooks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LaunchPenTool() {
  return window['go']['main']['App']['LaunchPenTool']();
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function SavePageImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePageImage'](arg1, arg2, arg3);
}

export function SelectPdfDialog() {
  return window['go']['main']['App']['SelectPdfDialog']();
}
