// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DownloadAndInstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1, arg2);
}

export function EnsureBookDir(arg1, arg2) {
  return window['go']['main']['App']['EnsureBookDir'](arg1, arg2);
}

export function EnsureBookDirWithOffset(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnsureBookDirWithOffset'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBookMetadata(arg1) {
  return window['go']['main']['App']['GetBookMetadata'](arg1);
}

export function GetLatestWeeklyPlan() {
  return window['go']['main']['App']['GetLatestWeeklyPlan']();
}

export function GetTextbooks() {
  return window['go']['main']['App']['GetTextbooks']();
}

export function GetWatchFolder() {
  return window['go']['main']['App']['GetWatchFolder']();
}

export function GetWeeklyPlanRawBase64(arg1) {
  return window['go']['main']['App']['GetWeeklyPlanRawBase64'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ParseWeeklyPlanFile(arg1) {
  return window['go']['main']['App']['ParseWeeklyPlanFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReanalyzeWeeklyPlan() {
  return window['go']['main']['App']['ReanalyzeWeeklyPlan']();
}

export function SavePageImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePageImage'](arg1, arg2, arg3);
}

export function SelectMultiplePdfsDialog() {
  return window['go']['main']['App']['SelectMultiplePdfsDialog']();
}

export function SelectPdfDialog() {
  return window['go']['main']['App']['SelectPdfDialog']();
}

export function SelectWatchFolderDialog() {
  return window['go']['main']['App']['SelectWatchFolderDialog']();
}

export function SelectWeeklyPlanFileDialog() {
  return window['go']['main']['App']['SelectWeeklyPlanFileDialog']();
}

export function SetWatchFolder(arg1) {
  return window['go']['main']['App']['SetWatchFolder'](arg1);
}

export function StartDrag() {
  return window['go']['main']['App']['StartDrag']();
}

export function UpdateBookOffset(arg1, arg2) {
  return window['go']['main']['App']['UpdateBookOffset'](arg1, arg2);
}
