// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function DeleteBook(arg1:string):Promise<void>;

export function DeleteMultipleBooks(arg1:Array<string>):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string):Promise<void>;

export function EnsureBookDir(arg1:string,arg2:number):Promise<void>;

export function EnsureBookDirWithOffset(arg1:string,arg2:number,arg3:number):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetBellSchedules():Promise<string>;

export function GetBookMetadata(arg1:string):Promise<main.Metadata>;

export function GetLatestWeeklyPlan():Promise<main.WeeklyPlanResult>;

export function GetTextbooks():Promise<Array<main.Textbook>>;

export function GetWatchFolder():Promise<string>;

export function GetWeeklyPlanRawBase64(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportBookFromImageFolder(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ParseWeeklyPlanFile(arg1:string):Promise<main.WeeklyPlanResult>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReanalyzeWeeklyPlan():Promise<main.WeeklyPlanResult>;

export function SaveBellSchedules(arg1:string):Promise<void>;

export function SavePageImage(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SaveWeeklyPlan(arg1:main.WeeklyPlanResult):Promise<void>;

export function ScanFolderForTextbooks(arg1:string):Promise<Array<main.UsbTextbookCandidate>>;

export function ScanUsbTextbooks():Promise<Array<main.UsbTextbookCandidate>>;

export function SelectDirectoryDialog(arg1:string):Promise<string>;

export function SelectMultiplePdfsDialog():Promise<Array<string>>;

export function SelectPdfDialog():Promise<string>;

export function SelectWatchFolderDialog():Promise<string>;

export function SelectWeeklyPlanFileDialog():Promise<main.WeeklyPlanResult>;

export function SetWatchFolder(arg1:string):Promise<void>;

export function StartDrag():Promise<void>;

export function UpdateBookOffset(arg1:string,arg2:number):Promise<void>;
