// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate(arg1:boolean):Promise<void>;

export function DeleteBook(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string):Promise<void>;

export function EnsureBookDir(arg1:string,arg2:number):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetTextbooks():Promise<Array<main.Textbook>>;

export function Greet(arg1:string):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function SavePageImage(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SelectPdfDialog():Promise<string>;

export function StartDrag():Promise<void>;
